
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#pragma once

#include <gtk/gtk.h>

G_BEGIN_DECLS

/* enumerations from "CheckersBoard.h" */
GType checkers_board_players_get_type (void) G_GNUC_CONST;
#define CHECKERS_TYPE_BOARD_PLAYERS (checkers_board_players_get_type ())

/* enumerations from "CheckersBoardButton.h" */
GType checkers_board_button_occupancy_get_type (void) G_GNUC_CONST;
#define CHECKERS_TYPE_BOARD_BUTTON_OCCUPANCY (checkers_board_button_occupancy_get_type ())
GType checkers_board_button_team_get_type (void) G_GNUC_CONST;
#define CHECKERS_TYPE_BOARD_BUTTON_TEAM (checkers_board_button_team_get_type ())
GType checkers_board_button_state_get_type (void) G_GNUC_CONST;
#define CHECKERS_TYPE_BOARD_BUTTON_STATE (checkers_board_button_state_get_type ())
G_END_DECLS

/* Generated data ends here */

