
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#include "includes.h"
/* enumerations from "CheckersBoard.h" */
GType
checkers_board_players_get_type (void)
{
  static gsize static_g_enum_type_id;

  if (g_once_init_enter (&static_g_enum_type_id))
    {
      static const GEnumValue values[] = {
            { CHECKERS_BOARD_EMPTY_BOARD, "CHECKERS_BOARD_EMPTY_BOARD", "empty-board" },
            { CHECKERS_BOARD_2_PLAYERS, "CHECKERS_BOARD_2_PLAYERS", "2-players" },
            { CHECKERS_BOARD_4_PLAYERS, "CHECKERS_BOARD_4_PLAYERS", "4-players" },
            { CHECKERS_BOARD_6_PLAYERS, "CHECKERS_BOARD_6_PLAYERS", "6-players" },
            { 0, NULL, NULL }
      };

      GType g_enum_type_id =
        g_enum_register_static (g_intern_static_string ("CheckersBoardPlayers"), values);

      g_once_init_leave (&static_g_enum_type_id, g_enum_type_id);
    }
  return static_g_enum_type_id;
}
/* enumerations from "CheckersBoardButton.h" */
GType
checkers_board_button_source_get_type (void)
{
  static gsize static_g_enum_type_id;

  if (g_once_init_enter (&static_g_enum_type_id))
    {
      static const GEnumValue values[] = {
            { CHECKERS_BOARD_BUTTON_EMPTY_SLOT, "CHECKERS_BOARD_BUTTON_EMPTY_SLOT", "empty-slot" },
            { CHECKERS_BOARD_BUTTON_RED_SLOT, "CHECKERS_BOARD_BUTTON_RED_SLOT", "red-slot" },
            { CHECKERS_BOARD_BUTTON_RED_BALL, "CHECKERS_BOARD_BUTTON_RED_BALL", "red-ball" },
            { CHECKERS_BOARD_BUTTON_BLUE_SLOT, "CHECKERS_BOARD_BUTTON_BLUE_SLOT", "blue-slot" },
            { CHECKERS_BOARD_BUTTON_BLUE_BALL, "CHECKERS_BOARD_BUTTON_BLUE_BALL", "blue-ball" },
            { CHECKERS_BOARD_BUTTON_GREEN_SLOT, "CHECKERS_BOARD_BUTTON_GREEN_SLOT", "green-slot" },
            { CHECKERS_BOARD_BUTTON_GREEN_BALL, "CHECKERS_BOARD_BUTTON_GREEN_BALL", "green-ball" },
            { CHECKERS_BOARD_BUTTON_BLACK_SLOT, "CHECKERS_BOARD_BUTTON_BLACK_SLOT", "black-slot" },
            { CHECKERS_BOARD_BUTTON_BLACK_BALL, "CHECKERS_BOARD_BUTTON_BLACK_BALL", "black-ball" },
            { CHECKERS_BOARD_BUTTON_YELLOW_SLOT, "CHECKERS_BOARD_BUTTON_YELLOW_SLOT", "yellow-slot" },
            { CHECKERS_BOARD_BUTTON_YELLOW_BALL, "CHECKERS_BOARD_BUTTON_YELLOW_BALL", "yellow-ball" },
            { CHECKERS_BOARD_BUTTON_WHITE_SLOT, "CHECKERS_BOARD_BUTTON_WHITE_SLOT", "white-slot" },
            { CHECKERS_BOARD_BUTTON_WHITE_BALL, "CHECKERS_BOARD_BUTTON_WHITE_BALL", "white-ball" },
            { 0, NULL, NULL }
      };

      GType g_enum_type_id =
        g_enum_register_static (g_intern_static_string ("CheckersBoardButtonSource"), values);

      g_once_init_leave (&static_g_enum_type_id, g_enum_type_id);
    }
  return static_g_enum_type_id;
}

/* Generated data ends here */

