
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#include "enum_types.h"
#include "checkers.h"
/* enumerations from "CheckersPlayers.h" */
GType
checkers_players_get_type (void)
{
  static gsize static_g_enum_type_id;

  if (g_once_init_enter (&static_g_enum_type_id))
    {
      static const GEnumValue values[] = {
            { CHECKERS_NO_PLAYERS, "CHECKERS_NO_PLAYERS", "no-players" },
            { CHECKERS_2_PLAYERS, "CHECKERS_2_PLAYERS", "2-players" },
            { CHECKERS_4_PLAYERS, "CHECKERS_4_PLAYERS", "4-players" },
            { CHECKERS_6_PLAYERS, "CHECKERS_6_PLAYERS", "6-players" },
            { 0, NULL, NULL }
      };

      GType g_enum_type_id =
        g_enum_register_static (g_intern_static_string ("CheckersPlayers"), values);

      g_once_init_leave (&static_g_enum_type_id, g_enum_type_id);
    }
  return static_g_enum_type_id;
}
/* enumerations from "CheckersSlot.h" */
GType
checkers_slot_occupancy_get_type (void)
{
  static gsize static_g_enum_type_id;

  if (g_once_init_enter (&static_g_enum_type_id))
    {
      static const GEnumValue values[] = {
            { CHECKERS_SLOT_UNOCCUPIED, "CHECKERS_SLOT_UNOCCUPIED", "unoccupied" },
            { CHECKERS_SLOT_OCCUPIED, "CHECKERS_SLOT_OCCUPIED", "occupied" },
            { 0, NULL, NULL }
      };

      GType g_enum_type_id =
        g_enum_register_static (g_intern_static_string ("CheckersSlotOccupancy"), values);

      g_once_init_leave (&static_g_enum_type_id, g_enum_type_id);
    }
  return static_g_enum_type_id;
}
GType
checkers_slot_state_get_type (void)
{
  static gsize static_g_enum_type_id;

  if (g_once_init_enter (&static_g_enum_type_id))
    {
      static const GEnumValue values[] = {
            { CHECKERS_SLOT_RED_SLOT, "CHECKERS_SLOT_RED_SLOT", "red-slot" },
            { CHECKERS_SLOT_RED_MARBLE, "CHECKERS_SLOT_RED_MARBLE", "red-marble" },
            { CHECKERS_SLOT_BLACK_SLOT, "CHECKERS_SLOT_BLACK_SLOT", "black-slot" },
            { CHECKERS_SLOT_BLACK_MARBLE, "CHECKERS_SLOT_BLACK_MARBLE", "black-marble" },
            { CHECKERS_SLOT_WHITE_SLOT, "CHECKERS_SLOT_WHITE_SLOT", "white-slot" },
            { CHECKERS_SLOT_WHITE_MARBLE, "CHECKERS_SLOT_WHITE_MARBLE", "white-marble" },
            { CHECKERS_SLOT_GREEN_SLOT, "CHECKERS_SLOT_GREEN_SLOT", "green-slot" },
            { CHECKERS_SLOT_GREEN_MARBLE, "CHECKERS_SLOT_GREEN_MARBLE", "green-marble" },
            { CHECKERS_SLOT_BLUE_SLOT, "CHECKERS_SLOT_BLUE_SLOT", "blue-slot" },
            { CHECKERS_SLOT_BLUE_MARBLE, "CHECKERS_SLOT_BLUE_MARBLE", "blue-marble" },
            { CHECKERS_SLOT_YELLOW_SLOT, "CHECKERS_SLOT_YELLOW_SLOT", "yellow-slot" },
            { CHECKERS_SLOT_YELLOW_MARBLE, "CHECKERS_SLOT_YELLOW_MARBLE", "yellow-marble" },
            { CHECKERS_SLOT_EMPTY_SLOT, "CHECKERS_SLOT_EMPTY_SLOT", "empty-slot" },
            { 0, NULL, NULL }
      };

      GType g_enum_type_id =
        g_enum_register_static (g_intern_static_string ("CheckersSlotState"), values);

      g_once_init_leave (&static_g_enum_type_id, g_enum_type_id);
    }
  return static_g_enum_type_id;
}
/* enumerations from "CheckersTeam.h" */
GType
checkers_team_get_type (void)
{
  static gsize static_g_enum_type_id;

  if (g_once_init_enter (&static_g_enum_type_id))
    {
      static const GEnumValue values[] = {
            { CHECKERS_RED_TEAM, "CHECKERS_RED_TEAM", "red-team" },
            { CHECKERS_BLACK_TEAM, "CHECKERS_BLACK_TEAM", "black-team" },
            { CHECKERS_WHITE_TEAM, "CHECKERS_WHITE_TEAM", "white-team" },
            { CHECKERS_GREEN_TEAM, "CHECKERS_GREEN_TEAM", "green-team" },
            { CHECKERS_BLUE_TEAM, "CHECKERS_BLUE_TEAM", "blue-team" },
            { CHECKERS_YELLOW_TEAM, "CHECKERS_YELLOW_TEAM", "yellow-team" },
            { CHECKERS_NO_TEAM, "CHECKERS_NO_TEAM", "no-team" },
            { 0, NULL, NULL }
      };

      GType g_enum_type_id =
        g_enum_register_static (g_intern_static_string ("CheckersTeam"), values);

      g_once_init_leave (&static_g_enum_type_id, g_enum_type_id);
    }
  return static_g_enum_type_id;
}

/* Generated data ends here */

